First test
lizethmendoza/protractor-workshop-2017 pull request #3
Opened 2017-10-04 19:38 UTC by lizethmendoza

Por favor revisar

2017-10-04 21:05 UTC, aperdomob requested changes
Debes agregar a los revisores para que nos lleguen notificaciones

![image](https://user-images.githubusercontent.com/17033942/31199714-e3e51396-a91d-11e7-8829-99c7c3c1daf1.png)

2017-10-04 21:05 UTC, aperdomob commented on protractor.config.js
> +}
EOF

2017-10-04 21:20 UTC, aperdomob commented
@lizethmendoza falta el EOF

2017-10-05 17:06 UTC, jhenaoz requested changes

2017-10-05 17:06 UTC, jhenaoz commented on protractor.config.js
> +}
para evitar esto deberias pensar en usar http://editorconfig.org/, asi evitar de manera automatica en tu editor de texto que se agregen estos archivos sin un fin de linea al final.

2017-10-05 19:03 UTC, lizethmendoza reviewed
Corregido

2017-10-05 19:21 UTC, aperdomob commented on protractor.config.js
> +}
Sigo viendo el EOF

2017-10-05 19:22 UTC, aperdomob commented on protractor.config.js
> +}
Sigo viendo que falta el EOF

2017-10-05 19:23 UTC, aperdomob requested changes
Corregir el EOF

2017-10-05 19:39 UTC, lizethmendoza commented
Corregido

2017-10-05 19:39 UTC, closed without merging